[project]
authors = ["Open Force Field Initiative <info@openforcefield.org>"]
channels = ["conda-forge"]
description = "Common utilities in the OpenFF software stack"
name = "openff-utilities-test"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "v0.1.9"

[tasks]

[dependencies]
python = "*"
versioneer-518 = "*"
pytest = "*"
pytest-cov = "*"
pytest-xdist = "*"
pytest-randomly = "*"
nbval = "*"
mypy = "*"
types-setuptools = "*"
types-toml = "*"
